### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by rajeshkalluri009** [flexmonster/pivot-kibana#15]
I installed flexmonster plugin with kibana 7.4.1 on ubuntu18.04 using the command 
1. kibana-plugin install https://github.com/flexmonster/pivotkibana/releases/download/v1.23/flexmonster_pivot-v1.23.zip
2. yarn upgrade
After relevant permission changes, finally the flexmonster icon is visible in kibana as per the demo shown.
But, after click no GUI is loaded. Screen is empty. 
When i checked the /var/log/syslog, the messages are repeating in this way

Nov 21 14:56:09 ubuntu-vm11 kibana[17937]: {"type":"response","@timestamp":"2019-11-21T09:26:09Z","tags":[],"pid":17937,"method":"get","statusCode":200,"req":{"url":"/api/flexmonster_pivot/es","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","accept":"application/json, text/plain, */*","kbn-version":"7.4.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","referer":"http://localhost:5601/app/flexmonster_pivot","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,ru;q=0.8,te;q=0.7"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://localhost:5601/app/flexmonster_pivot"},"res":{"statusCode":200,"responseTime":5,"contentLength":9},"message":"GET /api/flexmonster_pivot/es 200 5ms - 9.0B"}
Nov 21 14:56:09 ubuntu-vm11 kibana[17937]: {"type":"response","@timestamp":"2019-11-21T09:26:09Z","tags":[],"pid":17937,"method":"get","statusCode":304,"req":{"url":"/plugins/flexmonster_pivot/logo.png","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"http://localhost:5601/app/flexmonster_pivot","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,ru;q=0.8,te;q=0.7","if-none-match":"\"a7b1140aaf50ec7a9dadf8547eb63f6695ed2bf8\"","if-modified-since":"Tue, 19 Nov 2019 09:03:32 GMT"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://localhost:5601/app/flexmonster_pivot"},"res":{"statusCode":304,"responseTime":2,"contentLength":9},"message":"GET /plugins/flexmonster_pivot/logo.png 304 2ms - 9.0B"}
Nov 21 14:56:09 ubuntu-vm11 kibana[17937]: {"type":"response","@timestamp":"2019-11-21T09:26:09Z","tags":[],"pid":17937,"method":"get","statusCode":200,"req":{"url":"/api/spaces/space?purpose=any","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","kbn-version":"7.4.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","content-type":"application/json","accept":"*/*","referer":"http://localhost:5601/app/flexmonster_pivot","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,ru;q=0.8,te;q=0.7"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://localhost:5601/app/flexmonster_pivot"},"res":{"statusCode":200,"responseTime":8,"contentLength":9},"message":"GET /api/spaces/space?purpose=any 200 8ms - 9.0B"}

**Comment by tsshn** [comment]
Hello,
 
Thank you for reaching out to us.

Please, consider that release 1.21 of the plugin works with Kibana 7.3.2.

As for the Kibana 7.4.1, it seems that they made some breaking changes, and now the plugin does not work. Currently, we recommend making changes in the source code of the plugin to support the latest version of Kibana or using it with Kibana 7.3.2. For the latest versions, please make changes in the package.json and/or other files if necessary.

Feel free to contact us in case of additional questions occur.

Kind Regards,
Illia

**Comment by eryajf** [comment]
I changed my elk cluster version to 7.3.2 and pivot-kibana to 1.21. It didn't seem complicated to configure, but everything went well, but there was no corresponding icon in kibana

**Comment by tsshn** [comment]
Hello,

Thank you for your question.

We didn't manage to reproduce the issue using Kibana version 7.3.2 and plugin 1.21.

Our team kindly recommend restarting instances of Elasticsearch and Kibana.

We hope it helps.

Kind Regards,
Illia

**Comment by eryajf** [comment]
thanks, I will try it

**Comment by eryajf** [comment]
> Hello,
> 
> Thank you for your question.
> 
> We didn't manage to reproduce the issue using Kibana version 7.3.2 and plugin 1.21.
> 
> Our team kindly recommend restarting instances of Elasticsearch and Kibana.
> 
> We hope it helps.
> 
> Kind Regards,
> Illia

I redeployed the proper version in a new environment, but I still couldn't see this component in kibana. When I restarted kibana, I looked at the startup log and saw no output associated with pivot,This makes me very confused, do not know what configuration is still missing

**Comment by tsshn** [comment]
Hello,

Thank you for your feedback.

By default, the flexmonster_pivot kibana plugin is enabled.

It seems the plugin may be disabled in your case because of some specific configurations in the Kibana.
Our team kindly suggests checking the configurations on your end.

We would like to confirm that using the –flexmonster_pivot.enabled=true flag is also a feasible solution.

Also, we kindly recommend checking out whether the current system user has permission to access the folder where the plugin is placed.

Please let us know how everything goes for you.

Kind Regards,
Illia

**Comment by eryajf** [comment]
Thank you very much for your reply again. Inspired by your reply, I checked the plug-in directory permissions and executed the following two commands:

```
chown -R kibana.kibana /usr/share/kibana/plugins/flexmonster_pivot/
chmod -R 775 /usr/share/kibana/plugins/flexmonster_pivot/
```

Now when I configured elasticsearch and kibana after, I access kibana, it appears.

thanks again

**Comment by tsshn** [comment]
Hello,

Thank you for updating us on this.

We are happy to hear that your problem is resolved.

Regards,
Illia

**Comment by pankajdata4u** [comment]
I am using elasticsearch 7.4.2 and kibana 7.4.2 and your plugin 1.2.1 and done some changes as per the suggestions given here but still it is not loading the page with error on browser 

vendors.bundle.dll.js:417 TypeError: es is not a function
    at flexmonster_pivot.bundle.js:8
    at processQueue (vendors.bundle.dll.js:417)
    at vendors.bundle.dll.js:417
    at Scope.$digest (vendors.bundle.dll.js:417)
    at Scope.$apply (vendors.bundle.dll.js:417)
    at done (vendors.bundle.dll.js:417)
    at completeRequest (vendors.bundle.dll.js:417)
    at XMLHttpRequest.requestLoaded (vendors.bundle.dll.js:417) "Possibly unhandled rejection: {}"

Please let me know what we should do to make it work work with 7.4.2 as i cannot degrade elasticsearch to below version 7.3.2

I can see the icon on the page but page is blank.

**Comment by tsshn** [comment]
Hello,

Thank you for your question.

We would like to kindly inform you that the latest version 1.21 of the plugin works with Kibana 7.3.2.

For the latest versions, please make changes in the package.json and/or other files if necessary.

The suggestions provided within the current thread are relevant for Kibana version 7.3.2.

Regards,
Illia

**Comment by pankajdata4u** [comment]
Hi Tsshn,

Thanks for the reply. What exactly are the changes.

I have changed the below point in package.json

"kibana": {
    "version": "7.4.2",
then the logo start appearing
but still page is blank, is I am missing any configuration at any place.
Which file exactly we need to modify?

I tried modifying the elasticsearch dependencies packages but still problem remain same.
"dependencies": {
    "elasticsearch": "^16.0.0",
    "elasticsearch-browser": "^16.0.0",
I will be very helpful for your help.

**Comment by tsshn** [comment]
Hello,
 
Thank you for your feedback.
 
We would like to kindly inform you that our team can not provide an exact list of changes that have to be applied in order to make the plugin work with Kibana's latest versions.

You are welcome to investigate the problem on your side and modify the source code of the plugin placed on our GitHub in an appropriate way.

Regards,
Illia

**Comment by pankajdata4u** [comment]
Hi ,

I think its not the plugin issue but something else because i got below error in my log file 

{"type":"log","@timestamp":"2020-01-22T14:58:23Z","tags":["debug","plugins","security","basic"],"pid":18287,"message":"Trying to authenticate user request to /app/flexmonster_pivot."}
{"type":"log","@timestamp":"2020-01-22T14:58:23Z","tags":["security","app-authorization","debug"],"pid":18287,"message":"not authorizing - \"flexmonster_pivot\" isn't a protected application"}


I think resolving the issue may fix the problem.
Do you have any idea why it is happening.

Do i need to put something in kibana or elasticsearch headers. please suggest.

**Comment by tsshn** [comment]
Hello,

Thank you for providing detailed information.

However, we would like to kindly inform you that our team is not able to provide an exact solution for your case.

It may be of help to check out the following threads:
1. https://www.flexmonster.com/question/kibana-plugin-index-selection-not-working/
2. https://www.flexmonster.com/question/pivot-kibana-plugin-installation-eaccess-permission-denied/#answer-24176

Hope this helps.

Regards,
Illia
